version: '3.5'
services:
  linkmanagement:
    build: ./
    image: shortner/linkmanagement
    container_name: linkmanagement
    environment:
      - NODE_ENV=DEV
      - PORT=80
      - MONGO_URL=mongodb://db:27018/shortlinks
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - proxynet
    depends_on:
      - db
    
  db:
    image: mongo:latest
    container_name: linkmanagement_db
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    networks:
      - proxynet

networks:
  proxynet:
    name: shortner_network